### ISSUE TITLE
How did you installing Apex?

### ISSUE THREAD

**Issue by MingjieChen** [bshall/ZeroSpeech#4]
I am trying to run your code, but failed with an error with Apex

I install Apex by 

`conda install -c conda-forge nvidia-apex`

But I got an error:

> Traceback (most recent call last):
  File "train.py", line 123, in <module>
    train_model()
  File "/share/mini1/sw/std/python/anaconda3-2019.07/v3.7/envs/torch_1.4/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/share/mini1/sw/std/python/anaconda3-2019.07/v3.7/envs/torch_1.4/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/share/mini1/sw/std/python/anaconda3-2019.07/v3.7/envs/torch_1.4/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/share/mini1/sw/std/python/anaconda3-2019.07/v3.7/envs/torch_1.4/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 50, in train_model
    gamma=cfg.training.scheduler.gamma)
  File "/share/mini1/sw/std/python/anaconda3-2019.07/v3.7/envs/torch_1.4/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 382, in __init__
    super(MultiStepLR, self).__init__(optimizer, last_epoch)
  File "/share/mini1/sw/std/python/anaconda3-2019.07/v3.7/envs/torch_1.4/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 73, in __init__
    self.optimizer.step = with_counter(self.optimizer.step)
  File "/share/mini1/sw/std/python/anaconda3-2019.07/v3.7/envs/torch_1.4/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 55, in with_counter
    instance_ref = weakref.ref(method.__self__)
AttributeError: 'function' object has no attribute '__self__'

Similar bug was found here, but there is no way to fix yet https://github.com/NVIDIA/apex/issues/552

**Comment by bshall** [comment]
Hi @MingjieChen,

I just followed the instructions [here](https://github.com/NVIDIA/apex#linux).
Basically, the steps are:
```
$ git clone https://github.com/NVIDIA/apex
$ cd apex
$ pip install -v --no-cache-dir ./
```
I hope that helps.

**Comment by MingjieChen** [comment]
yes, it works.  
Thanks

**Comment by Geeks-Sid** [comment]
@MingjieChen Thank you very much that fixed it. I did not know that was an apex issue.
I hate this third library support, waiting for pytorch 1.6 .
